language: python
sudo: true

env:
  global:
  - OPENBLAS_NUM_THREADS=1
  - OMP_NUM_THREADS=1
  - MKL_NUM_THREADS=1

matrix:

  include:
    # Unit tests
    - os: linux
      env: TESTSUITE=unittests.sh PYTHON_VERSION="3.5" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - os: linux
      env: TESTSUITE=unittests.sh PYTHON_VERSION="3.6" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - os: linux
      env: TESTSUITE=unittests.sh PYTHON_VERSION="3.7" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download
  pip: true

git:
  depth: 5

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ `which conda` ]]; then echo 'Conda installation successful'; else exit 1; fi
  - conda create -n testenv --yes python=$PYTHON_VERSION pip wheel pytest gxx_linux-64 gcc_linux-64 swig
  - source activate testenv

install:
  - pip install pep8 codecov mypy flake8 pytest-cov
  - cat requirements.txt | xargs -n 1 -L 1 pip install
  - pip install .[all]

script:
  - ci_scripts/$TESTSUITE
