---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s] [%(asctime)s:%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: automl_toolkit.log

root:
  level: DEBUG
  handlers: [console, file_handler]
